<div class="menu">
  <div class="wrap">
    <div class="logo">LOGO</div>
    <ul>
      <li><a href="#">食玩圖鑑</a></li>
      <li><a href="#">食玩指南</a></li>
      <li><a href="#">食尚玩家</a></li>
      <li><a href="#">夜市新鮮事</a></li>
      <li><a href="#">創建指南</a></li>
      <li><a href="#" class="order">去點餐<i class="fas fa-arrow-right"></i></a></li>
      <li>
        <a href="#" class="user"><i class="fas fa-user"></i></a>
        <a href="#" class="cart"><i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
  </div>
</div>